export const Actions = {
  LOAD_STATE: 'LOAD_STATE',
  SET_ONBOARDED: 'SET_ONBOARDED',
  UPDATE_USER: 'UPDATE_USER',
  ADD_QUEST: 'ADD_QUEST',
  DELETE_QUEST: 'DELETE_QUEST',
  COMPLETE_MILESTONE: 'COMPLETE_MILESTONE',
  ADD_MILESTONE_PHOTO: 'ADD_MILESTONE_PHOTO',
  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  MARK_NOTIFICATIONS_READ: 'MARK_NOTIFICATIONS_READ',
  UNLOCK_BADGE: 'UNLOCK_BADGE',
  CHECK_STREAK: 'CHECK_STREAK',
} as const;
